### ISSUE TITLE
Training help

### ISSUE THREAD

**Issue by Yu-Wang-0801** [cvlab-yonsei/PISR#1]
Hello, when I found this kind of error during training, how should I modify the code? Thank you
![image](https://user-images.githubusercontent.com/49390007/87943403-929d1d80-cad0-11ea-8561-e237ca905141.png)

**Comment by wonkyunglee** [comment]
Hello, did you check if the Set5 dataset is located in ./data/benchmark/ folder correctly? 
Also, please ensure that the hierarchy of the Set5 folder is identical to the description at README.md.

**Comment by star-lunar** [comment]
I also met this problem.Haved you solved it?

**Comment by star-lunar** [comment]
> Hello, did you check if the Set5 dataset is located in ./data/benchmark/ folder correctly?
> Also, please ensure that the hierarchy of the Set5 folder is identical to the description at README.md.

I did it in this order but I still got this error

**Comment by Lininggggggg** [comment]
hello , haved you solved it?
