### ISSUE TITLE
Can we scale up 8 times??

### ISSUE THREAD

**Issue by SongDoHou** [cvlab-yonsei/PISR#10]
Hi, thanks for providing a code and wonderful research.

This model upscale 2, 3, 4 times. Can we set this model to 8 times scale up?

**Comment by wonkyunglee** [comment]
Thanks for your attention to our work. 
Well, I'm not sure it works. We didn't do any experiments on a scale of 8. 
But in my opinion, it may work because our framework shows general property and can be applied to several models/scales without bells and whistles.

**Comment by SongDoHou** [comment]
Thank you.
I appreciated your reply.
