### ISSUE TITLE
Hello,can you tell me how to test the model

### ISSUE THREAD

**Issue by AIFANLIN** [cvlab-yonsei/PISR#2]
can you tell me how to test the model

**Comment by wonkyunglee** [comment]
Sure :) First of all, you can check the PSNR of Set5 for every epoch during training. 
But I understand that you'd like to test the model after the end of the training.
I'll upload the evaluation code ASAP.

**Comment by wonkyunglee** [comment]
Hello, we updated the evaluation code on a master branch.
Please git clone again and follow the script. 
You can choose the benchmark datasets in 'configs/fsrcnn/base.ram.yml'
> python evaluate.py --config configs/fsrcnn/step2.yml

**Comment by star-lunar** [comment]
> can you tell me how to test the model

Hello, have you run the code yet? 
when I'm running step1_train_teacher.py with the metric best psnr :0.0. what was the problem

**Comment by star-lunar** [comment]
> can you tell me how to test the model

Hello, have you made any changes to the original author's code?

**Comment by AIFANLIN** [comment]
> > can you tell me how to test the model
> 
> Hello, have you made any changes to the original author's code?

预训练模型我跑通了，我没有更改过作者的代码哦，你遇到的问题，我也母鸡母鸡哦！抱歉！

**Comment by star-lunar** [comment]
谢谢你啦，我跑通了!是我数据集的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cvlab-yonsei/PISR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 中午11:28
收件人:&nbsp;"cvlab-yonsei/PISR"<PISR@noreply.github.com&gt;;
抄送:&nbsp;"SILENCE"<1769620606@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cvlab-yonsei/PISR] Hello,can you tell me how to test the model (#2)





   
can you tell me how to test the model
  
Hello, have you made any changes to the original author's code?
  
预训练模型我跑通了，我没有更改过作者的代码哦，你遇到的问题，我也母鸡母鸡哦！抱歉！
