### ISSUE TITLE
train student network

### ISSUE THREAD

**Issue by purse1996** [cvlab-yonsei/PISR#3]
when I train the student model and run 'python step2_train_student.py --config configs/fsrcnn/step2.yml', it returns the error that RuntimeError: CUDA out of memory. Tried to allocate 1.57 GiB (GPU 0; 10.76 GiB total capacity; 4.81 GiB already allocated; 1.21 GiB free; 8.77 GiB reserved in total by PyTorch). I reduce the batchsize to 4 in step2.yaml and use 4 gtx1080 Ti. The error still exists. Could you give me some suggestions?

**Comment by wonkyunglee** [comment]
Thank you for your attention to our research. Our code consists of a train, eval, test process.
I assume that the memory issue would occur during the test process. 
We've just updated the training and testing code, removing test procedures from the training codes.

**Comment by purse1996** [comment]
Thank you for your reply. In fact, when I remove the teacher network in the
evaluation, the code works.

Wonkyung Lee <notifications@github.com> 于2020年8月11日周二 下午12:46写道：

**Comment by wonkyunglee** [comment]
Nice work. We also removed the teacher network from evaluate.py. 
Thanks for the suggestion.
