### ISSUE TITLE
where is the Student network initialized with teacher network parameter?

### ISSUE THREAD

**Issue by ghost** [cvlab-yonsei/PISR#4]
Hi

Thanks for your code.

I'm reading the code with your paper and I saw that you stated initializing a student network with parameters from 

teacher network helped training faster.

But I couldn't see where the code is.

May be it's because I'm not so familiar with pytorch.

It'll very helpful if you tell me where the code initializing student network parameter is.

**Comment by wonkyunglee** [comment]
Hello, thanks for your attention. 
The initialization is implemented in a `load_pretrained_model()` method in `PISR/model/base.py`.
More specifically, the config file `PISR/configs/fsrcnn/step2.yml` has a configuration named "initialize_from", which is set to `results/fsrcnn/fsrcnn_teacher/checkpoint`.
It makes the parameters of the student model initialized from the teacher's parameters.

**Comment by ghost** [comment]
oh! I See

Thank you for your reply. I've learned a lot from your code.

thanks!
