### ISSUE TITLE
Could this method be applied to EDVR model?

### ISSUE THREAD

**Issue by leiwen83** [cvlab-yonsei/PISR#9]
Hi,

I am interested to know whether this compression method could be applied to very deep cnn like EDVR?

Thx,
Lei

**Comment by wonkyunglee** [comment]
Hello, Lei. 
Thanks for your attention to our work.
I think our method can be used for all SR models, but you may have to find appropriate hyperparameters to obtain a meaningful result.
Good luck.

**Comment by leiwen83** [comment]
I see.
Could you elaborate more details about how hyperparameters is determined, by autoML? or some other method?

Thx

**Comment by wonkyunglee** [comment]
We used a grid search.

**Comment by leiwen83** [comment]
Do you have any suggestion for tool using for grid search?
Like this: https://en.wikipedia.org/wiki/Hyperparameter_optimization#Grid_search ?

**Comment by wonkyunglee** [comment]
We didn't use any tools for the grid search. We changed config files, trained them, and compared them manually.

**Comment by leiwen83** [comment]
I see...
Thx
